# Server-Port
server:
  port: 80

root:
  uri: ${ROOT_URI}

spring:
  # PROFILES
  profiles:
    include: [mail, oauth, aws, slack, db]

# JWT
auth:
  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    accessTokenExpirationHour: ${JWT_ACCESS_TOKEN_EXPIRATION_HOUR}
    refreshTokenExpirationHour: ${JWT_REFRESH_TOKEN_EXPIRATION_HOUR}

# Cookie
app:
  cookie:
    expiry: ${COOKIE_EXPIRATION_TIME}